version: "3.4"
name: olympguide
services:
  frontend:
    build:
      context: ../Frontend/
      target: development
    ports:
     - "8000:8000"
  backend:
    build:
        context: ./OlympGuide/
    ports:
      - "8081:8080"
