version: "3.4"
name: olympguide
services:
  frontend:
    build:
      context: ../Frontend/
      dockerfile: ./Dockerfile.local
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../Frontend:/src
  backend:
    build:
      context: ./
      dockerfile: ./OlympGuide/Dockerfile.local
    ports:
      - "8081:8080"
