version: "3.4"
name: olympguide
services:
  frontend:
    build:
      context: ../Frontend/
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../Frontend:/src
  backend:
    build:
      context: ./OlympGuide/
    ports:
      - "8081:8080"
    environment:
      "ConnectionStrings_OlympGuideDB": "Host=db;Database=OlympGuide;Username=ogDbUser;Password=ogDbPasword" 
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: OlympGuide
      POSTGRES_USER: ogDbUser
      POSTGRES_PASSWORD: ogDbPasword
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}    