version: "3.4"
name: olympguide
services:
  frontend:
    build:
      context: ../Frontend/
      dockerfile: ./Dockerfile.local
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../Frontend:/src
  backend:
    build:
      context: ./
      dockerfile: ./OlympGuide/Dockerfile.local
    ports:
      - "8081:8080"
    environment:
      "ConnectionStrings__OlympGuideDB": "Host=postgres_db;Database=OlympGuide;Username=ogDbUser;Password=ogDbPassword"
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=ogDbUser
      - POSTGRES_PASSWORD=ogDbPassword
      - POSTGRES_DB=OlympGuide
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
