version: "3.4"
name: olympguide
services:
  frontend:
    build:
      context: ../Frontend/
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ../Frontend:/src
  backend:
    build:
        context: ./OlympGuide/
        dockerfile: ./OlympGuide/Dockerfile.local
    ports:
      - "8081:8080"
