apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.deployment.name }}
spec:
selector:
    matchLabels:
      app: {{ .Values.backend.deployment.name }}
  ports:
    - protocol: TCP
      port: 80 # The port the service is exposed on
      targetPort: 8080 # The target port on the container