name: helm-release
description: packages and releases the helm chart
inputs:
  helm-directory:
    description: directory of helm sources
    required: true
  k8s-token:
    description: k8s service account token
    required: true
  k8s-api:
    description: k8s api server
    required: true
  k8s-namespace:
    description: k8s namespace
    required: true
  helm-release-name:
    description: helm release name
    required: true
  helm-values-file:
    description: value file
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
    - name: configure kubectl
      shell: bash
      run: |-
        kubectl config set-credentials sa --token=${{ inputs.k8s-token }}
        kubectl config set-cluster default --server=${{ inputs.k8s-api }}
        kubectl config set-context sa/default --user=sa --cluster=default --namespace=${{ inputs.k8s-namespace }}
        kubectl config use-context sa/default
    - name: upgrading helm release 
      shell: bash
      run: |-
        helm package ${{ inputs.helm-directory }}
        package=$(find . -name "${CHART_NAME}*.tgz")
        echo $package
        helm upgrade ${{ inputs.helm-release-name }} $package -f ${{ github.workspace }}/${{ inputs.helm-directory }}/${{ inputs.helm-values-file }} --install -n ${{ inputs.k8s-namespace }} --wait
