name: helm-release
description: packages and releases the helm chart
inputs:
  helm-directory:
    description: directory of helm sources
    required: true
  k8s-token:
    description: k8s service account token
    required: true
  k8s-api:
    description: k8s api server
    required: true
  k8s-namespace:
    description: k8s namespace
    required: true
  helm-release-name:
    description: helm release name
    required: true
  helm-values-file:
    description: value file
    required: true
  helm-values-image-key:
    description: image key in values file
    required: true
  image-tag:
    description: image tag
    required: true
  kube-config:
    description: kube config
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
    - name: Create kube config
      shell: bash
      run: |
        mkdir -p ${HOME}/.kube
        echo "${{ inputs.kube-config }}" | base64 -d > ${HOME}/.kube/config
    - name: Use config
      shell: bash
      run: kubectl config use-context pm4-cluster
    - name: Upgrading helm release
      shell: bash
      run: |
        helm package ${{ github.workspace }}/${{ inputs.helm-directory }}
        package=$(find . -name "${CHART_NAME}*.tgz")
        echo "package file: ${{ github.workspace }}/${{ inputs.helm-directory }}/${{ inputs.helm-values-file }}"
        echo "image key-value: ${{ inputs.helm-values-image-key }}=${{ inputs.image-tag }}"
        helm upgrade ${{ inputs.helm-release-name }} $package -f ${{ github.workspace }}/${{ inputs.helm-directory }}/${{ inputs.helm-values-file }} --install -n ${{ inputs.k8s-namespace }} --set ${{ inputs.helm-values-image-key }}=${{ inputs.image-tag }} --wait
