backend:
  deployment:
    name: olympguide-backend
    replicas: 1
    forceRedeploy: false
    image:
      pullSecret: github-token-secret ## Key for Service Account Secret on K8s
      repository: ghcr.io/olympguide/backend/webserver
      pullPolicy: Always
      tag: latest
    resources:
      requests:
        memory: "250Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    port: 8080
  service:
    name: olympguide-backend
    port: 8080
    targetPort: 8080
  ingress:
    host: olympguide-backend.pm4.init-lab.ch
    path: /
    pathType: Prefix
  environment: Production
