backend:
  development:
    image:
      tag: latest
  production:
    image:
      tag: latest
  deployment:
    name: olympguide-backend
    replicas: 2
    forceRedeploy: true
    image:
      pullSecret: github-token-secret ## Key for Service Account Secret on K8s
      repository: ghcr.io/olympguide/backend/webserver
      pullPolicy: Always
    port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
