# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: coverage

on:
  push:
    branches: [ "KAN-78-coverage-pipeline" ]
  
permissions:
  contents: read
  packages: write

env:
  # GENERAL
  BACKEND_DIRECTORY: OlympGuide
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/webserver
  ORGANISATION: OlympGuide
  DOCKERFILE-PATH-DEVELOPMENT: Dockerfile.development
  # HELM env
  HELM_DIRECTORY: helm
  HELM_VALUES_FILE: values-stage.yaml
  HELM_RELEASE_NAME: olympguide-backend
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: olymp-guide-stage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.BACKEND_DIRECTORY }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.BACKEND_DIRECTORY }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.BACKEND_DIRECTORY }}
    - name: Collect Code Coverage Data
      run: dotnet test ./OlympGuideTests/OlympGuideTests.csproj  --collect:"XPlat Code Coverage" --results-directory ./OlympGuideTests/TestCoverageReport
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./OlympGuideTests/TestCoverageReport/**/coverage.cobertura.xml
