# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: production

on:
  push:
    branches: [ "main" ]
 
    ## Permissions
permissions:
  contents: read
  packages: write

env:
  # GENERAL
  BACKEND_DIRECTORY: OlympGuide
  # DOCKER env
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/webserver
  ORGANISATION: OlympGuide
  # HELM env
  HELM_DIRECTORY: helm
  HELM_RELEASE_NAME: olympguide
  # K8S env
  K8S_API: https://pm4.init-lab.ch/k8s/clusters/local
  K8S_NAMESPACE: olymp-guide-prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.BACKEND_DIRECTORY }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.BACKEND_DIRECTORY }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.BACKEND_DIRECTORY }}

  upload-artifact:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: create directory
        run: mkdir app
      - name: Build Project
        run: dotnet publish ./OlympGuide/OlympGuide.csproj -c Release -o ./app /p:UseAppHost=false
      - name: Display structure
        run: ls -R  

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: app/

  docker-build:
    needs: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: backend-artifact
          path: app/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Get latest tag
        id: latest-tag
        run: |
          echo "fetching tags"
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "version.${{ github.run_number }}")
          echo "parsed tag: $TAG"
          echo "image-tag=$TAG" >> $GITHUB_OUTPUT
       
      - name: download artifacts
        uses: actions/download-artifact@v4
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker login
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: extract metadata for docker image
        uses: docker/metadata-action@v5.5.1
        id: image-meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.latest-tag.outputs.image-tag }}
      - name: build and push docker image
        uses: docker/build-push-action@v5.2.0
        with:
          context: ./
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}    
          
  deploy-helm-ci:
    runs-on: ubuntu-22.04
    needs: [docker-build]
    environment: production

    steps:
      - name: checkout sources
        uses: actions/checkout@v4
      - name: deploy
        uses: ./.github/workflows/helm-release
        with:
          kube-config: ${{ secrets.KUBE_CONFIG }}
          helm-directory: ${{ env.HELM_DIRECTORY }}
          k8s-token: ${{ secrets.K8S_TOKEN }}
          k8s-api: ${{ env.K8S_API }}
          k8s-namespace: ${{ env.K8S_NAMESPACE }}
          helm-release-name: ${{ env.HELM_RELEASE_NAME }}
          helm-values-file: values.yaml
          image-tag: ${{ needs.docker-build.outputs.latest-tag }}
          helm-values-image-key: backend.production.image.tag