name: PR-Workflow
on:
  pull_request:
    branches: [ "main", "development"]
    types: [opened, synchronize]

env:
  # GENERAL
  BACKEND_DIRECTORY: OlympGuide
  # DOCKER env
  IMAGE_NAME: ${{ github.repository }}/webserver
  ORGANISATION: OlympGuide

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.BACKEND_DIRECTORY }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.BACKEND_DIRECTORY }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.BACKEND_DIRECTORY }}

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build . --file ./${{ env.BACKEND_DIRECTORY }}/Dockerfile.local

        
